name: meal
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+3

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  home_widget: ^0.6.0
  injectable: ^2.4.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  retrofit: ^4.1.0
  slang: ^3.31.1
  slang_flutter: ^3.31.0
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^14.2.1
  collection: ^1.18.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1
  freezed: ^2.5.2
  flutter_gen_runner: ^5.6.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  go_router_builder: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg

flutter_gen:
  integrations:
    flutter_svg: true
